#!/bin/bash

X16_EMU_PATH=/mnt/c/Users/Jennifer/Downloads/x16emu_win-r38

set -ex

cl65 -t cx16 -O -o weiqi16.prg weiqi16.c

cp ./weiqi16.prg $X16_EMU_PATH
cd $X16_EMU_PATH
./x16emu.exe -prg ./weiqi16.prg -debug -run
